### ISSUE TITLE
vscode Caddy was not found in your $PATH

### ISSUE THREAD

**Issue by olading-zxm** [caddyserver/vscode-caddyfile#294]
![image](https://user-images.githubusercontent.com/131647310/234199912-6ea7916a-842d-45e2-abdf-6c27ad1cf53e.png)
![image](https://user-images.githubusercontent.com/131647310/234199953-e275dd67-2a61-46fe-9aaf-ee1d33d33123.png)

Excuse me, how do I deal with this

**Comment by matthewpi** [comment]
I don't quite remember if or how it searches for binaries but you can manually set the path to Caddy using [`caddyfile.executable`](https://github.com/caddyserver/vscode-caddyfile#configuration).
